from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 444)
        MainWindow.setMinimumSize(QtCore.QSize(480, 444))
        MainWindow.setMaximumSize(QtCore.QSize(480, 444))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(130, 40, 231, 71))
        self.title.setStatusTip("")
        self.title.setStyleSheet("PY-DDOS")
        self.title.setObjectName("title")
        self.version_info = QtWidgets.QLabel(self.centralwidget)
        self.version_info.setGeometry(QtCore.QRect(310, 0, 171, 16))
        self.version_info.setObjectName("version_info")
        self.console = QtWidgets.QTextEdit(self.centralwidget)
        self.console.setGeometry(QtCore.QRect(240, 160, 231, 231))
        self.console.setReadOnly(True)
        self.console.setPlaceholderText("")
        self.console.setObjectName("console")
        self.ip_select = QtWidgets.QLineEdit(self.centralwidget)
        self.ip_select.setGeometry(QtCore.QRect(40, 170, 161, 20))
        self.ip_select.setObjectName("ip_select")
        self.port_select = QtWidgets.QLineEdit(self.centralwidget)
        self.port_select.setGeometry(QtCore.QRect(50, 210, 141, 20))
        self.port_select.setObjectName("port_select")
        self.threading_number = QtWidgets.QLineEdit(self.centralwidget)
        self.threading_number.setGeometry(QtCore.QRect(70, 250, 101, 20))
        self.threading_number.setObjectName("threading_number")
        self.console_title = QtWidgets.QLabel(self.centralwidget)
        self.console_title.setGeometry(QtCore.QRect(240, 140, 71, 16))
        self.console_title.setObjectName("console_title")
        self.start_atk = QtWidgets.QPushButton(self.centralwidget)
        self.start_atk.setGeometry(QtCore.QRect(20, 350, 75, 23))
        self.start_atk.setObjectName("start_atk")
        self.duration_input = QtWidgets.QLineEdit(self.centralwidget)
        self.duration_input.setGeometry(QtCore.QRect(90, 290, 51, 20))
        self.duration_input.setStyleSheet("")
        self.duration_input.setText("")
        self.duration_input.setObjectName("duration_input")
        self.atk_stop = QtWidgets.QPushButton(self.centralwidget)
        self.atk_stop.setGeometry(QtCore.QRect(130, 350, 75, 23))
        self.atk_stop.setObjectName("atk_stop")
        self.clear_console = QtWidgets.QPushButton(self.centralwidget)
        self.clear_console.setGeometry(QtCore.QRect(350, 390, 121, 20))
        self.clear_console.setObjectName("clear_console")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#0000ff;\">DDOS-GUI</span></p><p align=\"center\"><span style=\" font-weight:600; color:#aa0000;\">GUI by Fristine</span></p></body></html>"))
        self.version_info.setText(_translate("MainWindow", "<html><head/><body><p>Warning! this version is beta!</p></body></html>"))
        self.console.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.ip_select.setPlaceholderText(_translate("MainWindow", "target ip(xxx.xxx.xxx.xxx)"))
        self.port_select.setPlaceholderText(_translate("MainWindow", "target port(ex : 25565)"))
        self.threading_number.setPlaceholderText(_translate("MainWindow", "attack number"))
        self.console_title.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">CONSOLE</span></p></body></html>"))
        self.start_atk.setText(_translate("MainWindow", "START"))
        self.duration_input.setPlaceholderText(_translate("MainWindow", "duration"))
        self.atk_stop.setText(_translate("MainWindow", "STOP"))
        self.clear_console.setText(_translate("MainWindow", "CLEAR CONSOLE"))
